---
blackboard:
  is_testing: false
  is_blackboard: false

scr:
  wndw_name: OpenGL Renderer
  width: 800
  height: 600

settings:
  is_wireframeMode: false

colors:
   bg: #181818
   bg-alter: 0
   bg-second: 0