---
blackboard:
  is_testing: false
  is_blackboard: false

scr:
  wndw_name: OpenGL Renderer
  width: 800
  height: 600

settings:
  is_wireframeMode: false

colors:
   bg: #181818
   bg-alter: 0
   bg-second: 0

default_camera:
  near: 1.0
  far: 100
  fov: 45.0
  rotation_sensitivity: 0.02

default_lights:
  num_directional: 1
  num_point: 3
  num_spot: 1

default_animation:
  animate: false
  angle_multiplier: 0.0
  last_frame_time: 0.0
  emission_factor: 0.0